# Generated by Django 5.0.7 on 2024-07-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
